# development env

debug = false
salt = "111165de3c3adfb9dc4a79d1ca701111"
logfile = "/data/log/multCloudDev/multCloudDev.log"
name = "multCloudDev"
domain = "https://console.polymericcloud.com"
discount = 1.00
InstanceTypeFilePath="/data/log/multCloudDev/multCloudDev.log"
email=["xiangzuochang@cmcm.com","rongjunfeng@cmcm.com","zhujun@cmcm.com","zhaojie3@cmcm.com","lihaitao@cmcm.com","liyuguang@cmcm.com","zhangjing7@cmcm.com"]
env="pro"
lark_log_alert="https://open.feishu.cn/open-apis/bot/v2/hook/e5b67ec6-902e-4e55-9b49-0d9782439365"
platform="SaaS"
#platform="私有化"
log_collection_url="10.193.0.44:30318"
keystone_url="http://10.193.0.44:32613"
companyId=120
res=["compute","database","redis","loadbalance","mongodb", "elasticsearch","vpc","subnet","securityGroup","eip","bucket"]

[http]
listen = ":9090"
Exp = "168h"

[sdwanAgotoz]
Addr="https://openapi.agotoz.com"
Authorized="I7Ic1t1iF1uwJt-Ps6bKch51Sha9RsuC"

[counsel]
db = "/data/app/marshotspot/counsel.json"

[db]
addr = "@tcp(10.46.20.16:3306)/marshotspot?charset=utf8&&loc=Asia%2FShanghai&parseTime=true"
user = "marshotspot_pro"
pass = "AWqNdT/lC9h3xvqap9lJHKmyYsvufctcnYmSDRUCLn54yxHxYpeN4w=="
idle = 10
max = 20

[falcon]
addr = "http://10.46.122.90:8080"
name = "root"
sig = "server-side-cmcloud-token"
publicPass = "marshotspot_rsync"

[falconAlarm]
addr = "@tcp(10.46.27.103:3306)/alarms?charset=utf8&&loc=Asia%2FShanghai&parseTime=true"
user = "alarms_pro"
pass = "bkh6flz9tvcexd7yn8t3eu9vcz4k53r"

[falcon_graph]
addr = "@tcp(10.46.27.59:3306)/graph_plus?charset=utf8&&loc=Asia%2FShanghai&parseTime=true"
user = "graph_pro"
pass = "5yv46o2albwlv247wq8e1fonvfd4133"

[falcon_portal]
addr = "@tcp(10.46.27.51:3306)/falcon_portal_plus?loc=Local&parseTime=true"
user = "falcon_pro"
pass = "sphx6imk0k67314wy2ojaelg9wh74f"
noDataAddr = "10.46.122.90:6090"

[falcon_uic]
addr = "@tcp(10.46.27.133:3306)/uic_plus?loc=Local&parseTime=true"
user = "uic_pro"
pass = "4yido1ckrg6nw76v5i3nh4fqg56zbw"

[falcon_dashboard]
addr = "@tcp(10.46.27.108:3306)/dashboard_plus?charset=utf8&&loc=Asia%2FShanghai&parseTime=true"
user = "dashboard_pro"
pass = "8yuwnh94md976062zu63ynsw4vusw05"

[bill_mysql]
addr = "@tcp(10.46.20.222:3306)/marshotspot_billing?charset=utf8&&loc=Asia%2FShanghai&parseTime=true"
user = "marsh_billing_pro"
pass = "mbx1a81is1h7b20x6sjlsihds42k186i"

[mail]
host="ops.mail.cmcm.com"
port=25

[aws]
priceFileDir = "/data/app/marshotspot/aws/prices/"

[tt]
domain = "http://tt-marshotspot.cmcloud.org"

[bill]
BillDirectoryPath="/data/app/marshotspot/bill"
OriginBillDirectoryPath="/data/app/marshotspot/origin"
BucketName="multi-cloud-test"
BucketEndpoint="http://oss-cn-beijing.aliyuncs.com"

[influx]
addr="http://10.46.122.81:8086"
username="root"
userpass="abcd.1234"
database="open_falcon"

[redis]
addr="10.46.122.90:6379"
pass="QvXgna47Tsx6HcYodjPFXg=="

[mongo]
addr=["10.193.0.8:27017","10.193.0.11:27017","10.193.0.12:27017"]
user="polymericcloud"
pass="bZe7cdgoy1wdTuNTaHx2Olk9fCEvVAMt"
database="polymericcloud"

[marshotspotd]
logfile = "/data/log/multCloudDev/marshotspotd.log"


[cloud]
agent = "http://10.193.0.44:31439"

[message]
email="http://10.193.0.44:30566/api/message/email"
sms="http://10.193.0.44:30566/api/message/sms"

[nsq]
addrs=["10.46.122.81:4150"]
lookupds=["10.46.122.90:4161", "10.46.122.123:4161", "10.46.122.81:4161"]